#!/usr/bin/env bash
# Check if the required number of arguments are provided
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Transfer a file from the local client to a remote server via SCP (Secure Copy)

# Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]

# Parameters:
#   - PATH_TO_FILE: The local file to transfer
#   - IP: The IP address or hostname of the remote server
#   - USERNAME: The username to log in as on the remote server
#   - [PATH_TO_SSH_KEY]: (Optional) The path to the SSH private key file (default: use system SSH configuration)

# Options:
#   - -o StrictHostKeyChecking=no: Disable strict host key checking for the SCP command to avoid interactive prompts.

# Check if the SSH key path is provided (optional)
if [ $# -eq 4 ]; then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
