#!/usr/bin/env bash
# Description: Install Nginx web server and configure it to listen on port 80.
# Update the package list to ensure we have the latest package information.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
