#!/usr/bin/env bash
# Install, configure, and start the load balancer (HAProxy)

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# Load balancer configuration
DOMAIN_NAME='codeblu.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG="frontend http-in
    bind *:80
    default_backend backend_servers

backend backend_servers
    balance roundrobin
    server server1 52.87.222.90:80 check
    server server2 100.26.240.19:80 check"

# Create configuration files if they don't exist
[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

# Check if the configuration already exists in the file
CONFIG_WORDS=$(grep -Eco "backend backend_servers" < $CONFIG_FILE)

# Enable HAProxy if not already enabled
if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
    sudo sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
    echo 'ENABLED=1' >> $INIT_FILE
fi

# Add or update HAProxy configuration in the file
if [ "$CONFIG_WORDS" -eq 0 ]; then
    echo -e "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
else
    start_tkn="#--$DOMAIN_NAME-params-begin--"
    end_tkn="#--$DOMAIN_NAME-params-end--"
    a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    a=$((a - 1))
    b=$((b + 1))
    sed -i "$a,$b"d "$CONFIG_FILE"
    echo -en "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
fi

# Start or restart the HAProxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    service haproxy start
else
    service haproxy restart
fi
