#!/usr/bin/env bash
#a script that loops from 1 to 10 and:
#displays "bad luck" for the 4th iteration
#displays "good luck" for the 8th iteration
#displays "Best School" for the rest

i=0
while [ "$i" -lt 10 ]; do
    if [ "$i" -eq 4 ]; then
	echo "bad luck"
    elif [ "$i" -eq 8 ]; then
	echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
