#!/usr/bin/env bash
#a script that displays
#the content of the current directory
#In a list
#where only the part of the name after the first dash is displayed

for i in *; do
    if [[ "$i" != .* ]]; then
	name="${i##*/}"
	echo "- $name"
    fi
done
